#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 20
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_color_black = 1,
  sym_color_dark_blue = 2,
  sym_color_dark_green = 3,
  sym_color_dark_aqua = 4,
  sym_color_dark_red = 5,
  sym_color_dark_purple = 6,
  sym_color_gold = 7,
  sym_color_gray = 8,
  sym_color_dark_gray = 9,
  sym_color_blue = 10,
  anon_sym_u00a7a = 11,
  anon_sym_u00a7A = 12,
  anon_sym_u00a7b = 13,
  anon_sym_u00a7B = 14,
  anon_sym_u00a7c = 15,
  anon_sym_u00a7C = 16,
  anon_sym_u00a7d = 17,
  anon_sym_u00a7D = 18,
  anon_sym_u00a7e = 19,
  anon_sym_u00a7E = 20,
  anon_sym_u00a7f = 21,
  anon_sym_u00a7F = 22,
  anon_sym_u00a7g = 23,
  anon_sym_u00a7G = 24,
  anon_sym_u00a7k = 25,
  anon_sym_u00a7K = 26,
  anon_sym_u00a7l = 27,
  anon_sym_u00a7L = 28,
  anon_sym_u00a7m = 29,
  anon_sym_u00a7M = 30,
  anon_sym_u00a7n = 31,
  anon_sym_u00a7N = 32,
  anon_sym_u00a7o = 33,
  anon_sym_u00a7O = 34,
  anon_sym_u00a7r = 35,
  anon_sym_u00a7R = 36,
  anon_sym_DOLLAR_LBRACE = 37,
  aux_sym_variable_token1 = 38,
  anon_sym_RBRACE = 39,
  anon_sym_u00a7u00a7 = 40,
  anon_sym_u00a7 = 41,
  aux_sym_unknown_code_token1 = 42,
  sym_text = 43,
  sym_newline = 44,
  sym_source_file = 45,
  sym__token = 46,
  sym_color_green = 47,
  sym_color_aqua = 48,
  sym_color_red = 49,
  sym_color_light_purple = 50,
  sym_color_yellow = 51,
  sym_color_white = 52,
  sym_color_minecoin = 53,
  sym_fmt_obfuscate = 54,
  sym_fmt_bold = 55,
  sym_fmt_strike = 56,
  sym_fmt_underline = 57,
  sym_fmt_italic = 58,
  sym_fmt_reset = 59,
  sym_variable = 60,
  sym_escape_section = 61,
  sym_unknown_code = 62,
  aux_sym_source_file_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_color_black] = "color_black",
  [sym_color_dark_blue] = "color_dark_blue",
  [sym_color_dark_green] = "color_dark_green",
  [sym_color_dark_aqua] = "color_dark_aqua",
  [sym_color_dark_red] = "color_dark_red",
  [sym_color_dark_purple] = "color_dark_purple",
  [sym_color_gold] = "color_gold",
  [sym_color_gray] = "color_gray",
  [sym_color_dark_gray] = "color_dark_gray",
  [sym_color_blue] = "color_blue",
  [anon_sym_u00a7a] = "\u00a7a",
  [anon_sym_u00a7A] = "\u00a7A",
  [anon_sym_u00a7b] = "\u00a7b",
  [anon_sym_u00a7B] = "\u00a7B",
  [anon_sym_u00a7c] = "\u00a7c",
  [anon_sym_u00a7C] = "\u00a7C",
  [anon_sym_u00a7d] = "\u00a7d",
  [anon_sym_u00a7D] = "\u00a7D",
  [anon_sym_u00a7e] = "\u00a7e",
  [anon_sym_u00a7E] = "\u00a7E",
  [anon_sym_u00a7f] = "\u00a7f",
  [anon_sym_u00a7F] = "\u00a7F",
  [anon_sym_u00a7g] = "\u00a7g",
  [anon_sym_u00a7G] = "\u00a7G",
  [anon_sym_u00a7k] = "\u00a7k",
  [anon_sym_u00a7K] = "\u00a7K",
  [anon_sym_u00a7l] = "\u00a7l",
  [anon_sym_u00a7L] = "\u00a7L",
  [anon_sym_u00a7m] = "\u00a7m",
  [anon_sym_u00a7M] = "\u00a7M",
  [anon_sym_u00a7n] = "\u00a7n",
  [anon_sym_u00a7N] = "\u00a7N",
  [anon_sym_u00a7o] = "\u00a7o",
  [anon_sym_u00a7O] = "\u00a7O",
  [anon_sym_u00a7r] = "\u00a7r",
  [anon_sym_u00a7R] = "\u00a7R",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym_variable_token1] = "variable_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_u00a7u00a7] = "\u00a7\u00a7",
  [anon_sym_u00a7] = "\u00a7",
  [aux_sym_unknown_code_token1] = "unknown_code_token1",
  [sym_text] = "text",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym__token] = "_token",
  [sym_color_green] = "color_green",
  [sym_color_aqua] = "color_aqua",
  [sym_color_red] = "color_red",
  [sym_color_light_purple] = "color_light_purple",
  [sym_color_yellow] = "color_yellow",
  [sym_color_white] = "color_white",
  [sym_color_minecoin] = "color_minecoin",
  [sym_fmt_obfuscate] = "fmt_obfuscate",
  [sym_fmt_bold] = "fmt_bold",
  [sym_fmt_strike] = "fmt_strike",
  [sym_fmt_underline] = "fmt_underline",
  [sym_fmt_italic] = "fmt_italic",
  [sym_fmt_reset] = "fmt_reset",
  [sym_variable] = "variable",
  [sym_escape_section] = "escape_section",
  [sym_unknown_code] = "unknown_code",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_color_black] = sym_color_black,
  [sym_color_dark_blue] = sym_color_dark_blue,
  [sym_color_dark_green] = sym_color_dark_green,
  [sym_color_dark_aqua] = sym_color_dark_aqua,
  [sym_color_dark_red] = sym_color_dark_red,
  [sym_color_dark_purple] = sym_color_dark_purple,
  [sym_color_gold] = sym_color_gold,
  [sym_color_gray] = sym_color_gray,
  [sym_color_dark_gray] = sym_color_dark_gray,
  [sym_color_blue] = sym_color_blue,
  [anon_sym_u00a7a] = anon_sym_u00a7a,
  [anon_sym_u00a7A] = anon_sym_u00a7A,
  [anon_sym_u00a7b] = anon_sym_u00a7b,
  [anon_sym_u00a7B] = anon_sym_u00a7B,
  [anon_sym_u00a7c] = anon_sym_u00a7c,
  [anon_sym_u00a7C] = anon_sym_u00a7C,
  [anon_sym_u00a7d] = anon_sym_u00a7d,
  [anon_sym_u00a7D] = anon_sym_u00a7D,
  [anon_sym_u00a7e] = anon_sym_u00a7e,
  [anon_sym_u00a7E] = anon_sym_u00a7E,
  [anon_sym_u00a7f] = anon_sym_u00a7f,
  [anon_sym_u00a7F] = anon_sym_u00a7F,
  [anon_sym_u00a7g] = anon_sym_u00a7g,
  [anon_sym_u00a7G] = anon_sym_u00a7G,
  [anon_sym_u00a7k] = anon_sym_u00a7k,
  [anon_sym_u00a7K] = anon_sym_u00a7K,
  [anon_sym_u00a7l] = anon_sym_u00a7l,
  [anon_sym_u00a7L] = anon_sym_u00a7L,
  [anon_sym_u00a7m] = anon_sym_u00a7m,
  [anon_sym_u00a7M] = anon_sym_u00a7M,
  [anon_sym_u00a7n] = anon_sym_u00a7n,
  [anon_sym_u00a7N] = anon_sym_u00a7N,
  [anon_sym_u00a7o] = anon_sym_u00a7o,
  [anon_sym_u00a7O] = anon_sym_u00a7O,
  [anon_sym_u00a7r] = anon_sym_u00a7r,
  [anon_sym_u00a7R] = anon_sym_u00a7R,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym_variable_token1] = aux_sym_variable_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_u00a7u00a7] = anon_sym_u00a7u00a7,
  [anon_sym_u00a7] = anon_sym_u00a7,
  [aux_sym_unknown_code_token1] = aux_sym_unknown_code_token1,
  [sym_text] = sym_text,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym__token] = sym__token,
  [sym_color_green] = sym_color_green,
  [sym_color_aqua] = sym_color_aqua,
  [sym_color_red] = sym_color_red,
  [sym_color_light_purple] = sym_color_light_purple,
  [sym_color_yellow] = sym_color_yellow,
  [sym_color_white] = sym_color_white,
  [sym_color_minecoin] = sym_color_minecoin,
  [sym_fmt_obfuscate] = sym_fmt_obfuscate,
  [sym_fmt_bold] = sym_fmt_bold,
  [sym_fmt_strike] = sym_fmt_strike,
  [sym_fmt_underline] = sym_fmt_underline,
  [sym_fmt_italic] = sym_fmt_italic,
  [sym_fmt_reset] = sym_fmt_reset,
  [sym_variable] = sym_variable,
  [sym_escape_section] = sym_escape_section,
  [sym_unknown_code] = sym_unknown_code,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_color_black] = {
    .visible = true,
    .named = true,
  },
  [sym_color_dark_blue] = {
    .visible = true,
    .named = true,
  },
  [sym_color_dark_green] = {
    .visible = true,
    .named = true,
  },
  [sym_color_dark_aqua] = {
    .visible = true,
    .named = true,
  },
  [sym_color_dark_red] = {
    .visible = true,
    .named = true,
  },
  [sym_color_dark_purple] = {
    .visible = true,
    .named = true,
  },
  [sym_color_gold] = {
    .visible = true,
    .named = true,
  },
  [sym_color_gray] = {
    .visible = true,
    .named = true,
  },
  [sym_color_dark_gray] = {
    .visible = true,
    .named = true,
  },
  [sym_color_blue] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_u00a7a] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7A] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7B] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7c] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7F] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7g] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7G] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7k] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7K] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7l] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7L] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7m] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7M] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7N] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7o] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7O] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7R] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7u00a7] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00a7] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_unknown_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_color_green] = {
    .visible = true,
    .named = true,
  },
  [sym_color_aqua] = {
    .visible = true,
    .named = true,
  },
  [sym_color_red] = {
    .visible = true,
    .named = true,
  },
  [sym_color_light_purple] = {
    .visible = true,
    .named = true,
  },
  [sym_color_yellow] = {
    .visible = true,
    .named = true,
  },
  [sym_color_white] = {
    .visible = true,
    .named = true,
  },
  [sym_color_minecoin] = {
    .visible = true,
    .named = true,
  },
  [sym_fmt_obfuscate] = {
    .visible = true,
    .named = true,
  },
  [sym_fmt_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_fmt_strike] = {
    .visible = true,
    .named = true,
  },
  [sym_fmt_underline] = {
    .visible = true,
    .named = true,
  },
  [sym_fmt_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_fmt_reset] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_section] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_code] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
};

static TSCharacterRange aux_sym_unknown_code_token1_character_set_1[] = {
  {0, '\t'}, {0x0b, '\f'}, {0x0e, '#'}, {'%', '/'}, {':', '@'}, {'H', 'J'}, {'P', 'Q'}, {'S', '`'},
  {'h', 'j'}, {'p', 'q'}, {'s', 0xa6}, {0xa8, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(2);
      if (lookahead == '}') ADVANCE(45);
      if (lookahead == 0xa7) ADVANCE(47);
      if ((!eof && set_contains(aux_sym_unknown_code_token1_character_set_1, 12, lookahead))) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(52);
      END_STATE();
    case 2:
      if (lookahead == '{') ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '}') ADVANCE(45);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 4:
      if ((!eof && set_contains(aux_sym_unknown_code_token1_character_set_1, 12, lookahead))) ADVANCE(48);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(50);
      if (lookahead == 0xa7) ADVANCE(47);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_color_black);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_color_dark_blue);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_color_dark_green);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_color_dark_aqua);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_color_dark_red);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_color_dark_purple);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_color_gold);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_color_gray);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_color_dark_gray);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_color_blue);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_u00a7a);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_u00a7A);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_u00a7b);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_u00a7B);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_u00a7c);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_u00a7C);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_u00a7d);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_u00a7D);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_u00a7e);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_u00a7E);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_u00a7f);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_u00a7F);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_u00a7g);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_u00a7G);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_u00a7k);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_u00a7K);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_u00a7l);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_u00a7L);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_u00a7m);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_u00a7M);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_u00a7n);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_u00a7N);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_u00a7o);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_u00a7O);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_u00a7r);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_u00a7R);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_variable_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_u00a7u00a7);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_u00a7);
      ADVANCE_MAP(
        '0', 7,
        '1', 8,
        '2', 9,
        '3', 10,
        '4', 11,
        '5', 12,
        '6', 13,
        '7', 14,
        '8', 15,
        '9', 16,
        'A', 18,
        'B', 20,
        'C', 22,
        'D', 24,
        'E', 26,
        'F', 28,
        'G', 30,
        'K', 32,
        'L', 34,
        'M', 36,
        'N', 38,
        'O', 40,
        'R', 42,
        'a', 17,
        'b', 19,
        'c', 21,
        'd', 23,
        'e', 25,
        'f', 27,
        'g', 29,
        'k', 31,
        'l', 33,
        'm', 35,
        'n', 37,
        'o', 39,
        'r', 41,
        0xa7, 46,
      );
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_unknown_code_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$' &&
          lookahead != 0xa7) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_color_black] = ACTIONS(1),
    [sym_color_dark_blue] = ACTIONS(1),
    [sym_color_dark_green] = ACTIONS(1),
    [sym_color_dark_aqua] = ACTIONS(1),
    [sym_color_dark_red] = ACTIONS(1),
    [sym_color_dark_purple] = ACTIONS(1),
    [sym_color_gold] = ACTIONS(1),
    [sym_color_gray] = ACTIONS(1),
    [sym_color_dark_gray] = ACTIONS(1),
    [sym_color_blue] = ACTIONS(1),
    [anon_sym_u00a7a] = ACTIONS(1),
    [anon_sym_u00a7A] = ACTIONS(1),
    [anon_sym_u00a7b] = ACTIONS(1),
    [anon_sym_u00a7B] = ACTIONS(1),
    [anon_sym_u00a7c] = ACTIONS(1),
    [anon_sym_u00a7C] = ACTIONS(1),
    [anon_sym_u00a7d] = ACTIONS(1),
    [anon_sym_u00a7D] = ACTIONS(1),
    [anon_sym_u00a7e] = ACTIONS(1),
    [anon_sym_u00a7E] = ACTIONS(1),
    [anon_sym_u00a7f] = ACTIONS(1),
    [anon_sym_u00a7F] = ACTIONS(1),
    [anon_sym_u00a7g] = ACTIONS(1),
    [anon_sym_u00a7G] = ACTIONS(1),
    [anon_sym_u00a7k] = ACTIONS(1),
    [anon_sym_u00a7K] = ACTIONS(1),
    [anon_sym_u00a7l] = ACTIONS(1),
    [anon_sym_u00a7L] = ACTIONS(1),
    [anon_sym_u00a7m] = ACTIONS(1),
    [anon_sym_u00a7M] = ACTIONS(1),
    [anon_sym_u00a7n] = ACTIONS(1),
    [anon_sym_u00a7N] = ACTIONS(1),
    [anon_sym_u00a7o] = ACTIONS(1),
    [anon_sym_u00a7O] = ACTIONS(1),
    [anon_sym_u00a7r] = ACTIONS(1),
    [anon_sym_u00a7R] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_u00a7u00a7] = ACTIONS(1),
    [anon_sym_u00a7] = ACTIONS(1),
    [aux_sym_unknown_code_token1] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(21),
    [sym__token] = STATE(2),
    [sym_color_green] = STATE(2),
    [sym_color_aqua] = STATE(2),
    [sym_color_red] = STATE(2),
    [sym_color_light_purple] = STATE(2),
    [sym_color_yellow] = STATE(2),
    [sym_color_white] = STATE(2),
    [sym_color_minecoin] = STATE(2),
    [sym_fmt_obfuscate] = STATE(2),
    [sym_fmt_bold] = STATE(2),
    [sym_fmt_strike] = STATE(2),
    [sym_fmt_underline] = STATE(2),
    [sym_fmt_italic] = STATE(2),
    [sym_fmt_reset] = STATE(2),
    [sym_variable] = STATE(2),
    [sym_escape_section] = STATE(2),
    [sym_unknown_code] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_color_black] = ACTIONS(5),
    [sym_color_dark_blue] = ACTIONS(5),
    [sym_color_dark_green] = ACTIONS(5),
    [sym_color_dark_aqua] = ACTIONS(5),
    [sym_color_dark_red] = ACTIONS(5),
    [sym_color_dark_purple] = ACTIONS(5),
    [sym_color_gold] = ACTIONS(5),
    [sym_color_gray] = ACTIONS(5),
    [sym_color_dark_gray] = ACTIONS(5),
    [sym_color_blue] = ACTIONS(5),
    [anon_sym_u00a7a] = ACTIONS(7),
    [anon_sym_u00a7A] = ACTIONS(7),
    [anon_sym_u00a7b] = ACTIONS(9),
    [anon_sym_u00a7B] = ACTIONS(9),
    [anon_sym_u00a7c] = ACTIONS(11),
    [anon_sym_u00a7C] = ACTIONS(11),
    [anon_sym_u00a7d] = ACTIONS(13),
    [anon_sym_u00a7D] = ACTIONS(13),
    [anon_sym_u00a7e] = ACTIONS(15),
    [anon_sym_u00a7E] = ACTIONS(15),
    [anon_sym_u00a7f] = ACTIONS(17),
    [anon_sym_u00a7F] = ACTIONS(17),
    [anon_sym_u00a7g] = ACTIONS(19),
    [anon_sym_u00a7G] = ACTIONS(19),
    [anon_sym_u00a7k] = ACTIONS(21),
    [anon_sym_u00a7K] = ACTIONS(21),
    [anon_sym_u00a7l] = ACTIONS(23),
    [anon_sym_u00a7L] = ACTIONS(23),
    [anon_sym_u00a7m] = ACTIONS(25),
    [anon_sym_u00a7M] = ACTIONS(25),
    [anon_sym_u00a7n] = ACTIONS(27),
    [anon_sym_u00a7N] = ACTIONS(27),
    [anon_sym_u00a7o] = ACTIONS(29),
    [anon_sym_u00a7O] = ACTIONS(29),
    [anon_sym_u00a7r] = ACTIONS(31),
    [anon_sym_u00a7R] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_u00a7u00a7] = ACTIONS(35),
    [anon_sym_u00a7] = ACTIONS(37),
    [sym_text] = ACTIONS(39),
    [sym_newline] = ACTIONS(5),
  },
  [2] = {
    [sym__token] = STATE(3),
    [sym_color_green] = STATE(3),
    [sym_color_aqua] = STATE(3),
    [sym_color_red] = STATE(3),
    [sym_color_light_purple] = STATE(3),
    [sym_color_yellow] = STATE(3),
    [sym_color_white] = STATE(3),
    [sym_color_minecoin] = STATE(3),
    [sym_fmt_obfuscate] = STATE(3),
    [sym_fmt_bold] = STATE(3),
    [sym_fmt_strike] = STATE(3),
    [sym_fmt_underline] = STATE(3),
    [sym_fmt_italic] = STATE(3),
    [sym_fmt_reset] = STATE(3),
    [sym_variable] = STATE(3),
    [sym_escape_section] = STATE(3),
    [sym_unknown_code] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_color_black] = ACTIONS(43),
    [sym_color_dark_blue] = ACTIONS(43),
    [sym_color_dark_green] = ACTIONS(43),
    [sym_color_dark_aqua] = ACTIONS(43),
    [sym_color_dark_red] = ACTIONS(43),
    [sym_color_dark_purple] = ACTIONS(43),
    [sym_color_gold] = ACTIONS(43),
    [sym_color_gray] = ACTIONS(43),
    [sym_color_dark_gray] = ACTIONS(43),
    [sym_color_blue] = ACTIONS(43),
    [anon_sym_u00a7a] = ACTIONS(7),
    [anon_sym_u00a7A] = ACTIONS(7),
    [anon_sym_u00a7b] = ACTIONS(9),
    [anon_sym_u00a7B] = ACTIONS(9),
    [anon_sym_u00a7c] = ACTIONS(11),
    [anon_sym_u00a7C] = ACTIONS(11),
    [anon_sym_u00a7d] = ACTIONS(13),
    [anon_sym_u00a7D] = ACTIONS(13),
    [anon_sym_u00a7e] = ACTIONS(15),
    [anon_sym_u00a7E] = ACTIONS(15),
    [anon_sym_u00a7f] = ACTIONS(17),
    [anon_sym_u00a7F] = ACTIONS(17),
    [anon_sym_u00a7g] = ACTIONS(19),
    [anon_sym_u00a7G] = ACTIONS(19),
    [anon_sym_u00a7k] = ACTIONS(21),
    [anon_sym_u00a7K] = ACTIONS(21),
    [anon_sym_u00a7l] = ACTIONS(23),
    [anon_sym_u00a7L] = ACTIONS(23),
    [anon_sym_u00a7m] = ACTIONS(25),
    [anon_sym_u00a7M] = ACTIONS(25),
    [anon_sym_u00a7n] = ACTIONS(27),
    [anon_sym_u00a7N] = ACTIONS(27),
    [anon_sym_u00a7o] = ACTIONS(29),
    [anon_sym_u00a7O] = ACTIONS(29),
    [anon_sym_u00a7r] = ACTIONS(31),
    [anon_sym_u00a7R] = ACTIONS(31),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(33),
    [anon_sym_u00a7u00a7] = ACTIONS(35),
    [anon_sym_u00a7] = ACTIONS(37),
    [sym_text] = ACTIONS(45),
    [sym_newline] = ACTIONS(43),
  },
  [3] = {
    [sym__token] = STATE(3),
    [sym_color_green] = STATE(3),
    [sym_color_aqua] = STATE(3),
    [sym_color_red] = STATE(3),
    [sym_color_light_purple] = STATE(3),
    [sym_color_yellow] = STATE(3),
    [sym_color_white] = STATE(3),
    [sym_color_minecoin] = STATE(3),
    [sym_fmt_obfuscate] = STATE(3),
    [sym_fmt_bold] = STATE(3),
    [sym_fmt_strike] = STATE(3),
    [sym_fmt_underline] = STATE(3),
    [sym_fmt_italic] = STATE(3),
    [sym_fmt_reset] = STATE(3),
    [sym_variable] = STATE(3),
    [sym_escape_section] = STATE(3),
    [sym_unknown_code] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_color_black] = ACTIONS(49),
    [sym_color_dark_blue] = ACTIONS(49),
    [sym_color_dark_green] = ACTIONS(49),
    [sym_color_dark_aqua] = ACTIONS(49),
    [sym_color_dark_red] = ACTIONS(49),
    [sym_color_dark_purple] = ACTIONS(49),
    [sym_color_gold] = ACTIONS(49),
    [sym_color_gray] = ACTIONS(49),
    [sym_color_dark_gray] = ACTIONS(49),
    [sym_color_blue] = ACTIONS(49),
    [anon_sym_u00a7a] = ACTIONS(52),
    [anon_sym_u00a7A] = ACTIONS(52),
    [anon_sym_u00a7b] = ACTIONS(55),
    [anon_sym_u00a7B] = ACTIONS(55),
    [anon_sym_u00a7c] = ACTIONS(58),
    [anon_sym_u00a7C] = ACTIONS(58),
    [anon_sym_u00a7d] = ACTIONS(61),
    [anon_sym_u00a7D] = ACTIONS(61),
    [anon_sym_u00a7e] = ACTIONS(64),
    [anon_sym_u00a7E] = ACTIONS(64),
    [anon_sym_u00a7f] = ACTIONS(67),
    [anon_sym_u00a7F] = ACTIONS(67),
    [anon_sym_u00a7g] = ACTIONS(70),
    [anon_sym_u00a7G] = ACTIONS(70),
    [anon_sym_u00a7k] = ACTIONS(73),
    [anon_sym_u00a7K] = ACTIONS(73),
    [anon_sym_u00a7l] = ACTIONS(76),
    [anon_sym_u00a7L] = ACTIONS(76),
    [anon_sym_u00a7m] = ACTIONS(79),
    [anon_sym_u00a7M] = ACTIONS(79),
    [anon_sym_u00a7n] = ACTIONS(82),
    [anon_sym_u00a7N] = ACTIONS(82),
    [anon_sym_u00a7o] = ACTIONS(85),
    [anon_sym_u00a7O] = ACTIONS(85),
    [anon_sym_u00a7r] = ACTIONS(88),
    [anon_sym_u00a7R] = ACTIONS(88),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(91),
    [anon_sym_u00a7u00a7] = ACTIONS(94),
    [anon_sym_u00a7] = ACTIONS(97),
    [sym_text] = ACTIONS(100),
    [sym_newline] = ACTIONS(49),
  },
  [4] = {
    [ts_builtin_sym_end] = ACTIONS(103),
    [sym_color_black] = ACTIONS(103),
    [sym_color_dark_blue] = ACTIONS(103),
    [sym_color_dark_green] = ACTIONS(103),
    [sym_color_dark_aqua] = ACTIONS(103),
    [sym_color_dark_red] = ACTIONS(103),
    [sym_color_dark_purple] = ACTIONS(103),
    [sym_color_gold] = ACTIONS(103),
    [sym_color_gray] = ACTIONS(103),
    [sym_color_dark_gray] = ACTIONS(103),
    [sym_color_blue] = ACTIONS(103),
    [anon_sym_u00a7a] = ACTIONS(103),
    [anon_sym_u00a7A] = ACTIONS(103),
    [anon_sym_u00a7b] = ACTIONS(103),
    [anon_sym_u00a7B] = ACTIONS(103),
    [anon_sym_u00a7c] = ACTIONS(103),
    [anon_sym_u00a7C] = ACTIONS(103),
    [anon_sym_u00a7d] = ACTIONS(103),
    [anon_sym_u00a7D] = ACTIONS(103),
    [anon_sym_u00a7e] = ACTIONS(103),
    [anon_sym_u00a7E] = ACTIONS(103),
    [anon_sym_u00a7f] = ACTIONS(103),
    [anon_sym_u00a7F] = ACTIONS(103),
    [anon_sym_u00a7g] = ACTIONS(103),
    [anon_sym_u00a7G] = ACTIONS(103),
    [anon_sym_u00a7k] = ACTIONS(103),
    [anon_sym_u00a7K] = ACTIONS(103),
    [anon_sym_u00a7l] = ACTIONS(103),
    [anon_sym_u00a7L] = ACTIONS(103),
    [anon_sym_u00a7m] = ACTIONS(103),
    [anon_sym_u00a7M] = ACTIONS(103),
    [anon_sym_u00a7n] = ACTIONS(103),
    [anon_sym_u00a7N] = ACTIONS(103),
    [anon_sym_u00a7o] = ACTIONS(103),
    [anon_sym_u00a7O] = ACTIONS(103),
    [anon_sym_u00a7r] = ACTIONS(103),
    [anon_sym_u00a7R] = ACTIONS(103),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(103),
    [anon_sym_u00a7u00a7] = ACTIONS(103),
    [anon_sym_u00a7] = ACTIONS(105),
    [sym_text] = ACTIONS(105),
    [sym_newline] = ACTIONS(103),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym_color_black] = ACTIONS(107),
    [sym_color_dark_blue] = ACTIONS(107),
    [sym_color_dark_green] = ACTIONS(107),
    [sym_color_dark_aqua] = ACTIONS(107),
    [sym_color_dark_red] = ACTIONS(107),
    [sym_color_dark_purple] = ACTIONS(107),
    [sym_color_gold] = ACTIONS(107),
    [sym_color_gray] = ACTIONS(107),
    [sym_color_dark_gray] = ACTIONS(107),
    [sym_color_blue] = ACTIONS(107),
    [anon_sym_u00a7a] = ACTIONS(107),
    [anon_sym_u00a7A] = ACTIONS(107),
    [anon_sym_u00a7b] = ACTIONS(107),
    [anon_sym_u00a7B] = ACTIONS(107),
    [anon_sym_u00a7c] = ACTIONS(107),
    [anon_sym_u00a7C] = ACTIONS(107),
    [anon_sym_u00a7d] = ACTIONS(107),
    [anon_sym_u00a7D] = ACTIONS(107),
    [anon_sym_u00a7e] = ACTIONS(107),
    [anon_sym_u00a7E] = ACTIONS(107),
    [anon_sym_u00a7f] = ACTIONS(107),
    [anon_sym_u00a7F] = ACTIONS(107),
    [anon_sym_u00a7g] = ACTIONS(107),
    [anon_sym_u00a7G] = ACTIONS(107),
    [anon_sym_u00a7k] = ACTIONS(107),
    [anon_sym_u00a7K] = ACTIONS(107),
    [anon_sym_u00a7l] = ACTIONS(107),
    [anon_sym_u00a7L] = ACTIONS(107),
    [anon_sym_u00a7m] = ACTIONS(107),
    [anon_sym_u00a7M] = ACTIONS(107),
    [anon_sym_u00a7n] = ACTIONS(107),
    [anon_sym_u00a7N] = ACTIONS(107),
    [anon_sym_u00a7o] = ACTIONS(107),
    [anon_sym_u00a7O] = ACTIONS(107),
    [anon_sym_u00a7r] = ACTIONS(107),
    [anon_sym_u00a7R] = ACTIONS(107),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(107),
    [anon_sym_u00a7u00a7] = ACTIONS(107),
    [anon_sym_u00a7] = ACTIONS(109),
    [sym_text] = ACTIONS(109),
    [sym_newline] = ACTIONS(107),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym_color_black] = ACTIONS(111),
    [sym_color_dark_blue] = ACTIONS(111),
    [sym_color_dark_green] = ACTIONS(111),
    [sym_color_dark_aqua] = ACTIONS(111),
    [sym_color_dark_red] = ACTIONS(111),
    [sym_color_dark_purple] = ACTIONS(111),
    [sym_color_gold] = ACTIONS(111),
    [sym_color_gray] = ACTIONS(111),
    [sym_color_dark_gray] = ACTIONS(111),
    [sym_color_blue] = ACTIONS(111),
    [anon_sym_u00a7a] = ACTIONS(111),
    [anon_sym_u00a7A] = ACTIONS(111),
    [anon_sym_u00a7b] = ACTIONS(111),
    [anon_sym_u00a7B] = ACTIONS(111),
    [anon_sym_u00a7c] = ACTIONS(111),
    [anon_sym_u00a7C] = ACTIONS(111),
    [anon_sym_u00a7d] = ACTIONS(111),
    [anon_sym_u00a7D] = ACTIONS(111),
    [anon_sym_u00a7e] = ACTIONS(111),
    [anon_sym_u00a7E] = ACTIONS(111),
    [anon_sym_u00a7f] = ACTIONS(111),
    [anon_sym_u00a7F] = ACTIONS(111),
    [anon_sym_u00a7g] = ACTIONS(111),
    [anon_sym_u00a7G] = ACTIONS(111),
    [anon_sym_u00a7k] = ACTIONS(111),
    [anon_sym_u00a7K] = ACTIONS(111),
    [anon_sym_u00a7l] = ACTIONS(111),
    [anon_sym_u00a7L] = ACTIONS(111),
    [anon_sym_u00a7m] = ACTIONS(111),
    [anon_sym_u00a7M] = ACTIONS(111),
    [anon_sym_u00a7n] = ACTIONS(111),
    [anon_sym_u00a7N] = ACTIONS(111),
    [anon_sym_u00a7o] = ACTIONS(111),
    [anon_sym_u00a7O] = ACTIONS(111),
    [anon_sym_u00a7r] = ACTIONS(111),
    [anon_sym_u00a7R] = ACTIONS(111),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(111),
    [anon_sym_u00a7u00a7] = ACTIONS(111),
    [anon_sym_u00a7] = ACTIONS(113),
    [sym_text] = ACTIONS(113),
    [sym_newline] = ACTIONS(111),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(115),
    [sym_color_black] = ACTIONS(115),
    [sym_color_dark_blue] = ACTIONS(115),
    [sym_color_dark_green] = ACTIONS(115),
    [sym_color_dark_aqua] = ACTIONS(115),
    [sym_color_dark_red] = ACTIONS(115),
    [sym_color_dark_purple] = ACTIONS(115),
    [sym_color_gold] = ACTIONS(115),
    [sym_color_gray] = ACTIONS(115),
    [sym_color_dark_gray] = ACTIONS(115),
    [sym_color_blue] = ACTIONS(115),
    [anon_sym_u00a7a] = ACTIONS(115),
    [anon_sym_u00a7A] = ACTIONS(115),
    [anon_sym_u00a7b] = ACTIONS(115),
    [anon_sym_u00a7B] = ACTIONS(115),
    [anon_sym_u00a7c] = ACTIONS(115),
    [anon_sym_u00a7C] = ACTIONS(115),
    [anon_sym_u00a7d] = ACTIONS(115),
    [anon_sym_u00a7D] = ACTIONS(115),
    [anon_sym_u00a7e] = ACTIONS(115),
    [anon_sym_u00a7E] = ACTIONS(115),
    [anon_sym_u00a7f] = ACTIONS(115),
    [anon_sym_u00a7F] = ACTIONS(115),
    [anon_sym_u00a7g] = ACTIONS(115),
    [anon_sym_u00a7G] = ACTIONS(115),
    [anon_sym_u00a7k] = ACTIONS(115),
    [anon_sym_u00a7K] = ACTIONS(115),
    [anon_sym_u00a7l] = ACTIONS(115),
    [anon_sym_u00a7L] = ACTIONS(115),
    [anon_sym_u00a7m] = ACTIONS(115),
    [anon_sym_u00a7M] = ACTIONS(115),
    [anon_sym_u00a7n] = ACTIONS(115),
    [anon_sym_u00a7N] = ACTIONS(115),
    [anon_sym_u00a7o] = ACTIONS(115),
    [anon_sym_u00a7O] = ACTIONS(115),
    [anon_sym_u00a7r] = ACTIONS(115),
    [anon_sym_u00a7R] = ACTIONS(115),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(115),
    [anon_sym_u00a7u00a7] = ACTIONS(115),
    [anon_sym_u00a7] = ACTIONS(117),
    [sym_text] = ACTIONS(117),
    [sym_newline] = ACTIONS(115),
  },
  [8] = {
    [ts_builtin_sym_end] = ACTIONS(119),
    [sym_color_black] = ACTIONS(119),
    [sym_color_dark_blue] = ACTIONS(119),
    [sym_color_dark_green] = ACTIONS(119),
    [sym_color_dark_aqua] = ACTIONS(119),
    [sym_color_dark_red] = ACTIONS(119),
    [sym_color_dark_purple] = ACTIONS(119),
    [sym_color_gold] = ACTIONS(119),
    [sym_color_gray] = ACTIONS(119),
    [sym_color_dark_gray] = ACTIONS(119),
    [sym_color_blue] = ACTIONS(119),
    [anon_sym_u00a7a] = ACTIONS(119),
    [anon_sym_u00a7A] = ACTIONS(119),
    [anon_sym_u00a7b] = ACTIONS(119),
    [anon_sym_u00a7B] = ACTIONS(119),
    [anon_sym_u00a7c] = ACTIONS(119),
    [anon_sym_u00a7C] = ACTIONS(119),
    [anon_sym_u00a7d] = ACTIONS(119),
    [anon_sym_u00a7D] = ACTIONS(119),
    [anon_sym_u00a7e] = ACTIONS(119),
    [anon_sym_u00a7E] = ACTIONS(119),
    [anon_sym_u00a7f] = ACTIONS(119),
    [anon_sym_u00a7F] = ACTIONS(119),
    [anon_sym_u00a7g] = ACTIONS(119),
    [anon_sym_u00a7G] = ACTIONS(119),
    [anon_sym_u00a7k] = ACTIONS(119),
    [anon_sym_u00a7K] = ACTIONS(119),
    [anon_sym_u00a7l] = ACTIONS(119),
    [anon_sym_u00a7L] = ACTIONS(119),
    [anon_sym_u00a7m] = ACTIONS(119),
    [anon_sym_u00a7M] = ACTIONS(119),
    [anon_sym_u00a7n] = ACTIONS(119),
    [anon_sym_u00a7N] = ACTIONS(119),
    [anon_sym_u00a7o] = ACTIONS(119),
    [anon_sym_u00a7O] = ACTIONS(119),
    [anon_sym_u00a7r] = ACTIONS(119),
    [anon_sym_u00a7R] = ACTIONS(119),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(119),
    [anon_sym_u00a7u00a7] = ACTIONS(119),
    [anon_sym_u00a7] = ACTIONS(121),
    [sym_text] = ACTIONS(121),
    [sym_newline] = ACTIONS(119),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(123),
    [sym_color_black] = ACTIONS(123),
    [sym_color_dark_blue] = ACTIONS(123),
    [sym_color_dark_green] = ACTIONS(123),
    [sym_color_dark_aqua] = ACTIONS(123),
    [sym_color_dark_red] = ACTIONS(123),
    [sym_color_dark_purple] = ACTIONS(123),
    [sym_color_gold] = ACTIONS(123),
    [sym_color_gray] = ACTIONS(123),
    [sym_color_dark_gray] = ACTIONS(123),
    [sym_color_blue] = ACTIONS(123),
    [anon_sym_u00a7a] = ACTIONS(123),
    [anon_sym_u00a7A] = ACTIONS(123),
    [anon_sym_u00a7b] = ACTIONS(123),
    [anon_sym_u00a7B] = ACTIONS(123),
    [anon_sym_u00a7c] = ACTIONS(123),
    [anon_sym_u00a7C] = ACTIONS(123),
    [anon_sym_u00a7d] = ACTIONS(123),
    [anon_sym_u00a7D] = ACTIONS(123),
    [anon_sym_u00a7e] = ACTIONS(123),
    [anon_sym_u00a7E] = ACTIONS(123),
    [anon_sym_u00a7f] = ACTIONS(123),
    [anon_sym_u00a7F] = ACTIONS(123),
    [anon_sym_u00a7g] = ACTIONS(123),
    [anon_sym_u00a7G] = ACTIONS(123),
    [anon_sym_u00a7k] = ACTIONS(123),
    [anon_sym_u00a7K] = ACTIONS(123),
    [anon_sym_u00a7l] = ACTIONS(123),
    [anon_sym_u00a7L] = ACTIONS(123),
    [anon_sym_u00a7m] = ACTIONS(123),
    [anon_sym_u00a7M] = ACTIONS(123),
    [anon_sym_u00a7n] = ACTIONS(123),
    [anon_sym_u00a7N] = ACTIONS(123),
    [anon_sym_u00a7o] = ACTIONS(123),
    [anon_sym_u00a7O] = ACTIONS(123),
    [anon_sym_u00a7r] = ACTIONS(123),
    [anon_sym_u00a7R] = ACTIONS(123),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(123),
    [anon_sym_u00a7u00a7] = ACTIONS(123),
    [anon_sym_u00a7] = ACTIONS(125),
    [sym_text] = ACTIONS(125),
    [sym_newline] = ACTIONS(123),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(127),
    [sym_color_black] = ACTIONS(127),
    [sym_color_dark_blue] = ACTIONS(127),
    [sym_color_dark_green] = ACTIONS(127),
    [sym_color_dark_aqua] = ACTIONS(127),
    [sym_color_dark_red] = ACTIONS(127),
    [sym_color_dark_purple] = ACTIONS(127),
    [sym_color_gold] = ACTIONS(127),
    [sym_color_gray] = ACTIONS(127),
    [sym_color_dark_gray] = ACTIONS(127),
    [sym_color_blue] = ACTIONS(127),
    [anon_sym_u00a7a] = ACTIONS(127),
    [anon_sym_u00a7A] = ACTIONS(127),
    [anon_sym_u00a7b] = ACTIONS(127),
    [anon_sym_u00a7B] = ACTIONS(127),
    [anon_sym_u00a7c] = ACTIONS(127),
    [anon_sym_u00a7C] = ACTIONS(127),
    [anon_sym_u00a7d] = ACTIONS(127),
    [anon_sym_u00a7D] = ACTIONS(127),
    [anon_sym_u00a7e] = ACTIONS(127),
    [anon_sym_u00a7E] = ACTIONS(127),
    [anon_sym_u00a7f] = ACTIONS(127),
    [anon_sym_u00a7F] = ACTIONS(127),
    [anon_sym_u00a7g] = ACTIONS(127),
    [anon_sym_u00a7G] = ACTIONS(127),
    [anon_sym_u00a7k] = ACTIONS(127),
    [anon_sym_u00a7K] = ACTIONS(127),
    [anon_sym_u00a7l] = ACTIONS(127),
    [anon_sym_u00a7L] = ACTIONS(127),
    [anon_sym_u00a7m] = ACTIONS(127),
    [anon_sym_u00a7M] = ACTIONS(127),
    [anon_sym_u00a7n] = ACTIONS(127),
    [anon_sym_u00a7N] = ACTIONS(127),
    [anon_sym_u00a7o] = ACTIONS(127),
    [anon_sym_u00a7O] = ACTIONS(127),
    [anon_sym_u00a7r] = ACTIONS(127),
    [anon_sym_u00a7R] = ACTIONS(127),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(127),
    [anon_sym_u00a7u00a7] = ACTIONS(127),
    [anon_sym_u00a7] = ACTIONS(129),
    [sym_text] = ACTIONS(129),
    [sym_newline] = ACTIONS(127),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(131),
    [sym_color_black] = ACTIONS(131),
    [sym_color_dark_blue] = ACTIONS(131),
    [sym_color_dark_green] = ACTIONS(131),
    [sym_color_dark_aqua] = ACTIONS(131),
    [sym_color_dark_red] = ACTIONS(131),
    [sym_color_dark_purple] = ACTIONS(131),
    [sym_color_gold] = ACTIONS(131),
    [sym_color_gray] = ACTIONS(131),
    [sym_color_dark_gray] = ACTIONS(131),
    [sym_color_blue] = ACTIONS(131),
    [anon_sym_u00a7a] = ACTIONS(131),
    [anon_sym_u00a7A] = ACTIONS(131),
    [anon_sym_u00a7b] = ACTIONS(131),
    [anon_sym_u00a7B] = ACTIONS(131),
    [anon_sym_u00a7c] = ACTIONS(131),
    [anon_sym_u00a7C] = ACTIONS(131),
    [anon_sym_u00a7d] = ACTIONS(131),
    [anon_sym_u00a7D] = ACTIONS(131),
    [anon_sym_u00a7e] = ACTIONS(131),
    [anon_sym_u00a7E] = ACTIONS(131),
    [anon_sym_u00a7f] = ACTIONS(131),
    [anon_sym_u00a7F] = ACTIONS(131),
    [anon_sym_u00a7g] = ACTIONS(131),
    [anon_sym_u00a7G] = ACTIONS(131),
    [anon_sym_u00a7k] = ACTIONS(131),
    [anon_sym_u00a7K] = ACTIONS(131),
    [anon_sym_u00a7l] = ACTIONS(131),
    [anon_sym_u00a7L] = ACTIONS(131),
    [anon_sym_u00a7m] = ACTIONS(131),
    [anon_sym_u00a7M] = ACTIONS(131),
    [anon_sym_u00a7n] = ACTIONS(131),
    [anon_sym_u00a7N] = ACTIONS(131),
    [anon_sym_u00a7o] = ACTIONS(131),
    [anon_sym_u00a7O] = ACTIONS(131),
    [anon_sym_u00a7r] = ACTIONS(131),
    [anon_sym_u00a7R] = ACTIONS(131),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(131),
    [anon_sym_u00a7u00a7] = ACTIONS(131),
    [anon_sym_u00a7] = ACTIONS(133),
    [sym_text] = ACTIONS(133),
    [sym_newline] = ACTIONS(131),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(135),
    [sym_color_black] = ACTIONS(135),
    [sym_color_dark_blue] = ACTIONS(135),
    [sym_color_dark_green] = ACTIONS(135),
    [sym_color_dark_aqua] = ACTIONS(135),
    [sym_color_dark_red] = ACTIONS(135),
    [sym_color_dark_purple] = ACTIONS(135),
    [sym_color_gold] = ACTIONS(135),
    [sym_color_gray] = ACTIONS(135),
    [sym_color_dark_gray] = ACTIONS(135),
    [sym_color_blue] = ACTIONS(135),
    [anon_sym_u00a7a] = ACTIONS(135),
    [anon_sym_u00a7A] = ACTIONS(135),
    [anon_sym_u00a7b] = ACTIONS(135),
    [anon_sym_u00a7B] = ACTIONS(135),
    [anon_sym_u00a7c] = ACTIONS(135),
    [anon_sym_u00a7C] = ACTIONS(135),
    [anon_sym_u00a7d] = ACTIONS(135),
    [anon_sym_u00a7D] = ACTIONS(135),
    [anon_sym_u00a7e] = ACTIONS(135),
    [anon_sym_u00a7E] = ACTIONS(135),
    [anon_sym_u00a7f] = ACTIONS(135),
    [anon_sym_u00a7F] = ACTIONS(135),
    [anon_sym_u00a7g] = ACTIONS(135),
    [anon_sym_u00a7G] = ACTIONS(135),
    [anon_sym_u00a7k] = ACTIONS(135),
    [anon_sym_u00a7K] = ACTIONS(135),
    [anon_sym_u00a7l] = ACTIONS(135),
    [anon_sym_u00a7L] = ACTIONS(135),
    [anon_sym_u00a7m] = ACTIONS(135),
    [anon_sym_u00a7M] = ACTIONS(135),
    [anon_sym_u00a7n] = ACTIONS(135),
    [anon_sym_u00a7N] = ACTIONS(135),
    [anon_sym_u00a7o] = ACTIONS(135),
    [anon_sym_u00a7O] = ACTIONS(135),
    [anon_sym_u00a7r] = ACTIONS(135),
    [anon_sym_u00a7R] = ACTIONS(135),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(135),
    [anon_sym_u00a7u00a7] = ACTIONS(135),
    [anon_sym_u00a7] = ACTIONS(137),
    [sym_text] = ACTIONS(137),
    [sym_newline] = ACTIONS(135),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(139),
    [sym_color_black] = ACTIONS(139),
    [sym_color_dark_blue] = ACTIONS(139),
    [sym_color_dark_green] = ACTIONS(139),
    [sym_color_dark_aqua] = ACTIONS(139),
    [sym_color_dark_red] = ACTIONS(139),
    [sym_color_dark_purple] = ACTIONS(139),
    [sym_color_gold] = ACTIONS(139),
    [sym_color_gray] = ACTIONS(139),
    [sym_color_dark_gray] = ACTIONS(139),
    [sym_color_blue] = ACTIONS(139),
    [anon_sym_u00a7a] = ACTIONS(139),
    [anon_sym_u00a7A] = ACTIONS(139),
    [anon_sym_u00a7b] = ACTIONS(139),
    [anon_sym_u00a7B] = ACTIONS(139),
    [anon_sym_u00a7c] = ACTIONS(139),
    [anon_sym_u00a7C] = ACTIONS(139),
    [anon_sym_u00a7d] = ACTIONS(139),
    [anon_sym_u00a7D] = ACTIONS(139),
    [anon_sym_u00a7e] = ACTIONS(139),
    [anon_sym_u00a7E] = ACTIONS(139),
    [anon_sym_u00a7f] = ACTIONS(139),
    [anon_sym_u00a7F] = ACTIONS(139),
    [anon_sym_u00a7g] = ACTIONS(139),
    [anon_sym_u00a7G] = ACTIONS(139),
    [anon_sym_u00a7k] = ACTIONS(139),
    [anon_sym_u00a7K] = ACTIONS(139),
    [anon_sym_u00a7l] = ACTIONS(139),
    [anon_sym_u00a7L] = ACTIONS(139),
    [anon_sym_u00a7m] = ACTIONS(139),
    [anon_sym_u00a7M] = ACTIONS(139),
    [anon_sym_u00a7n] = ACTIONS(139),
    [anon_sym_u00a7N] = ACTIONS(139),
    [anon_sym_u00a7o] = ACTIONS(139),
    [anon_sym_u00a7O] = ACTIONS(139),
    [anon_sym_u00a7r] = ACTIONS(139),
    [anon_sym_u00a7R] = ACTIONS(139),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(139),
    [anon_sym_u00a7u00a7] = ACTIONS(139),
    [anon_sym_u00a7] = ACTIONS(141),
    [sym_text] = ACTIONS(141),
    [sym_newline] = ACTIONS(139),
  },
  [14] = {
    [ts_builtin_sym_end] = ACTIONS(143),
    [sym_color_black] = ACTIONS(143),
    [sym_color_dark_blue] = ACTIONS(143),
    [sym_color_dark_green] = ACTIONS(143),
    [sym_color_dark_aqua] = ACTIONS(143),
    [sym_color_dark_red] = ACTIONS(143),
    [sym_color_dark_purple] = ACTIONS(143),
    [sym_color_gold] = ACTIONS(143),
    [sym_color_gray] = ACTIONS(143),
    [sym_color_dark_gray] = ACTIONS(143),
    [sym_color_blue] = ACTIONS(143),
    [anon_sym_u00a7a] = ACTIONS(143),
    [anon_sym_u00a7A] = ACTIONS(143),
    [anon_sym_u00a7b] = ACTIONS(143),
    [anon_sym_u00a7B] = ACTIONS(143),
    [anon_sym_u00a7c] = ACTIONS(143),
    [anon_sym_u00a7C] = ACTIONS(143),
    [anon_sym_u00a7d] = ACTIONS(143),
    [anon_sym_u00a7D] = ACTIONS(143),
    [anon_sym_u00a7e] = ACTIONS(143),
    [anon_sym_u00a7E] = ACTIONS(143),
    [anon_sym_u00a7f] = ACTIONS(143),
    [anon_sym_u00a7F] = ACTIONS(143),
    [anon_sym_u00a7g] = ACTIONS(143),
    [anon_sym_u00a7G] = ACTIONS(143),
    [anon_sym_u00a7k] = ACTIONS(143),
    [anon_sym_u00a7K] = ACTIONS(143),
    [anon_sym_u00a7l] = ACTIONS(143),
    [anon_sym_u00a7L] = ACTIONS(143),
    [anon_sym_u00a7m] = ACTIONS(143),
    [anon_sym_u00a7M] = ACTIONS(143),
    [anon_sym_u00a7n] = ACTIONS(143),
    [anon_sym_u00a7N] = ACTIONS(143),
    [anon_sym_u00a7o] = ACTIONS(143),
    [anon_sym_u00a7O] = ACTIONS(143),
    [anon_sym_u00a7r] = ACTIONS(143),
    [anon_sym_u00a7R] = ACTIONS(143),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(143),
    [anon_sym_u00a7u00a7] = ACTIONS(143),
    [anon_sym_u00a7] = ACTIONS(145),
    [sym_text] = ACTIONS(145),
    [sym_newline] = ACTIONS(143),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(147),
    [sym_color_black] = ACTIONS(147),
    [sym_color_dark_blue] = ACTIONS(147),
    [sym_color_dark_green] = ACTIONS(147),
    [sym_color_dark_aqua] = ACTIONS(147),
    [sym_color_dark_red] = ACTIONS(147),
    [sym_color_dark_purple] = ACTIONS(147),
    [sym_color_gold] = ACTIONS(147),
    [sym_color_gray] = ACTIONS(147),
    [sym_color_dark_gray] = ACTIONS(147),
    [sym_color_blue] = ACTIONS(147),
    [anon_sym_u00a7a] = ACTIONS(147),
    [anon_sym_u00a7A] = ACTIONS(147),
    [anon_sym_u00a7b] = ACTIONS(147),
    [anon_sym_u00a7B] = ACTIONS(147),
    [anon_sym_u00a7c] = ACTIONS(147),
    [anon_sym_u00a7C] = ACTIONS(147),
    [anon_sym_u00a7d] = ACTIONS(147),
    [anon_sym_u00a7D] = ACTIONS(147),
    [anon_sym_u00a7e] = ACTIONS(147),
    [anon_sym_u00a7E] = ACTIONS(147),
    [anon_sym_u00a7f] = ACTIONS(147),
    [anon_sym_u00a7F] = ACTIONS(147),
    [anon_sym_u00a7g] = ACTIONS(147),
    [anon_sym_u00a7G] = ACTIONS(147),
    [anon_sym_u00a7k] = ACTIONS(147),
    [anon_sym_u00a7K] = ACTIONS(147),
    [anon_sym_u00a7l] = ACTIONS(147),
    [anon_sym_u00a7L] = ACTIONS(147),
    [anon_sym_u00a7m] = ACTIONS(147),
    [anon_sym_u00a7M] = ACTIONS(147),
    [anon_sym_u00a7n] = ACTIONS(147),
    [anon_sym_u00a7N] = ACTIONS(147),
    [anon_sym_u00a7o] = ACTIONS(147),
    [anon_sym_u00a7O] = ACTIONS(147),
    [anon_sym_u00a7r] = ACTIONS(147),
    [anon_sym_u00a7R] = ACTIONS(147),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(147),
    [anon_sym_u00a7u00a7] = ACTIONS(147),
    [anon_sym_u00a7] = ACTIONS(149),
    [sym_text] = ACTIONS(149),
    [sym_newline] = ACTIONS(147),
  },
  [16] = {
    [ts_builtin_sym_end] = ACTIONS(151),
    [sym_color_black] = ACTIONS(151),
    [sym_color_dark_blue] = ACTIONS(151),
    [sym_color_dark_green] = ACTIONS(151),
    [sym_color_dark_aqua] = ACTIONS(151),
    [sym_color_dark_red] = ACTIONS(151),
    [sym_color_dark_purple] = ACTIONS(151),
    [sym_color_gold] = ACTIONS(151),
    [sym_color_gray] = ACTIONS(151),
    [sym_color_dark_gray] = ACTIONS(151),
    [sym_color_blue] = ACTIONS(151),
    [anon_sym_u00a7a] = ACTIONS(151),
    [anon_sym_u00a7A] = ACTIONS(151),
    [anon_sym_u00a7b] = ACTIONS(151),
    [anon_sym_u00a7B] = ACTIONS(151),
    [anon_sym_u00a7c] = ACTIONS(151),
    [anon_sym_u00a7C] = ACTIONS(151),
    [anon_sym_u00a7d] = ACTIONS(151),
    [anon_sym_u00a7D] = ACTIONS(151),
    [anon_sym_u00a7e] = ACTIONS(151),
    [anon_sym_u00a7E] = ACTIONS(151),
    [anon_sym_u00a7f] = ACTIONS(151),
    [anon_sym_u00a7F] = ACTIONS(151),
    [anon_sym_u00a7g] = ACTIONS(151),
    [anon_sym_u00a7G] = ACTIONS(151),
    [anon_sym_u00a7k] = ACTIONS(151),
    [anon_sym_u00a7K] = ACTIONS(151),
    [anon_sym_u00a7l] = ACTIONS(151),
    [anon_sym_u00a7L] = ACTIONS(151),
    [anon_sym_u00a7m] = ACTIONS(151),
    [anon_sym_u00a7M] = ACTIONS(151),
    [anon_sym_u00a7n] = ACTIONS(151),
    [anon_sym_u00a7N] = ACTIONS(151),
    [anon_sym_u00a7o] = ACTIONS(151),
    [anon_sym_u00a7O] = ACTIONS(151),
    [anon_sym_u00a7r] = ACTIONS(151),
    [anon_sym_u00a7R] = ACTIONS(151),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(151),
    [anon_sym_u00a7u00a7] = ACTIONS(151),
    [anon_sym_u00a7] = ACTIONS(153),
    [sym_text] = ACTIONS(153),
    [sym_newline] = ACTIONS(151),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(155),
    [sym_color_black] = ACTIONS(155),
    [sym_color_dark_blue] = ACTIONS(155),
    [sym_color_dark_green] = ACTIONS(155),
    [sym_color_dark_aqua] = ACTIONS(155),
    [sym_color_dark_red] = ACTIONS(155),
    [sym_color_dark_purple] = ACTIONS(155),
    [sym_color_gold] = ACTIONS(155),
    [sym_color_gray] = ACTIONS(155),
    [sym_color_dark_gray] = ACTIONS(155),
    [sym_color_blue] = ACTIONS(155),
    [anon_sym_u00a7a] = ACTIONS(155),
    [anon_sym_u00a7A] = ACTIONS(155),
    [anon_sym_u00a7b] = ACTIONS(155),
    [anon_sym_u00a7B] = ACTIONS(155),
    [anon_sym_u00a7c] = ACTIONS(155),
    [anon_sym_u00a7C] = ACTIONS(155),
    [anon_sym_u00a7d] = ACTIONS(155),
    [anon_sym_u00a7D] = ACTIONS(155),
    [anon_sym_u00a7e] = ACTIONS(155),
    [anon_sym_u00a7E] = ACTIONS(155),
    [anon_sym_u00a7f] = ACTIONS(155),
    [anon_sym_u00a7F] = ACTIONS(155),
    [anon_sym_u00a7g] = ACTIONS(155),
    [anon_sym_u00a7G] = ACTIONS(155),
    [anon_sym_u00a7k] = ACTIONS(155),
    [anon_sym_u00a7K] = ACTIONS(155),
    [anon_sym_u00a7l] = ACTIONS(155),
    [anon_sym_u00a7L] = ACTIONS(155),
    [anon_sym_u00a7m] = ACTIONS(155),
    [anon_sym_u00a7M] = ACTIONS(155),
    [anon_sym_u00a7n] = ACTIONS(155),
    [anon_sym_u00a7N] = ACTIONS(155),
    [anon_sym_u00a7o] = ACTIONS(155),
    [anon_sym_u00a7O] = ACTIONS(155),
    [anon_sym_u00a7r] = ACTIONS(155),
    [anon_sym_u00a7R] = ACTIONS(155),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(155),
    [anon_sym_u00a7u00a7] = ACTIONS(155),
    [anon_sym_u00a7] = ACTIONS(157),
    [sym_text] = ACTIONS(157),
    [sym_newline] = ACTIONS(155),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(159),
    [sym_color_black] = ACTIONS(159),
    [sym_color_dark_blue] = ACTIONS(159),
    [sym_color_dark_green] = ACTIONS(159),
    [sym_color_dark_aqua] = ACTIONS(159),
    [sym_color_dark_red] = ACTIONS(159),
    [sym_color_dark_purple] = ACTIONS(159),
    [sym_color_gold] = ACTIONS(159),
    [sym_color_gray] = ACTIONS(159),
    [sym_color_dark_gray] = ACTIONS(159),
    [sym_color_blue] = ACTIONS(159),
    [anon_sym_u00a7a] = ACTIONS(159),
    [anon_sym_u00a7A] = ACTIONS(159),
    [anon_sym_u00a7b] = ACTIONS(159),
    [anon_sym_u00a7B] = ACTIONS(159),
    [anon_sym_u00a7c] = ACTIONS(159),
    [anon_sym_u00a7C] = ACTIONS(159),
    [anon_sym_u00a7d] = ACTIONS(159),
    [anon_sym_u00a7D] = ACTIONS(159),
    [anon_sym_u00a7e] = ACTIONS(159),
    [anon_sym_u00a7E] = ACTIONS(159),
    [anon_sym_u00a7f] = ACTIONS(159),
    [anon_sym_u00a7F] = ACTIONS(159),
    [anon_sym_u00a7g] = ACTIONS(159),
    [anon_sym_u00a7G] = ACTIONS(159),
    [anon_sym_u00a7k] = ACTIONS(159),
    [anon_sym_u00a7K] = ACTIONS(159),
    [anon_sym_u00a7l] = ACTIONS(159),
    [anon_sym_u00a7L] = ACTIONS(159),
    [anon_sym_u00a7m] = ACTIONS(159),
    [anon_sym_u00a7M] = ACTIONS(159),
    [anon_sym_u00a7n] = ACTIONS(159),
    [anon_sym_u00a7N] = ACTIONS(159),
    [anon_sym_u00a7o] = ACTIONS(159),
    [anon_sym_u00a7O] = ACTIONS(159),
    [anon_sym_u00a7r] = ACTIONS(159),
    [anon_sym_u00a7R] = ACTIONS(159),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(159),
    [anon_sym_u00a7u00a7] = ACTIONS(159),
    [anon_sym_u00a7] = ACTIONS(161),
    [sym_text] = ACTIONS(161),
    [sym_newline] = ACTIONS(159),
  },
  [19] = {
    [ts_builtin_sym_end] = ACTIONS(163),
    [sym_color_black] = ACTIONS(163),
    [sym_color_dark_blue] = ACTIONS(163),
    [sym_color_dark_green] = ACTIONS(163),
    [sym_color_dark_aqua] = ACTIONS(163),
    [sym_color_dark_red] = ACTIONS(163),
    [sym_color_dark_purple] = ACTIONS(163),
    [sym_color_gold] = ACTIONS(163),
    [sym_color_gray] = ACTIONS(163),
    [sym_color_dark_gray] = ACTIONS(163),
    [sym_color_blue] = ACTIONS(163),
    [anon_sym_u00a7a] = ACTIONS(163),
    [anon_sym_u00a7A] = ACTIONS(163),
    [anon_sym_u00a7b] = ACTIONS(163),
    [anon_sym_u00a7B] = ACTIONS(163),
    [anon_sym_u00a7c] = ACTIONS(163),
    [anon_sym_u00a7C] = ACTIONS(163),
    [anon_sym_u00a7d] = ACTIONS(163),
    [anon_sym_u00a7D] = ACTIONS(163),
    [anon_sym_u00a7e] = ACTIONS(163),
    [anon_sym_u00a7E] = ACTIONS(163),
    [anon_sym_u00a7f] = ACTIONS(163),
    [anon_sym_u00a7F] = ACTIONS(163),
    [anon_sym_u00a7g] = ACTIONS(163),
    [anon_sym_u00a7G] = ACTIONS(163),
    [anon_sym_u00a7k] = ACTIONS(163),
    [anon_sym_u00a7K] = ACTIONS(163),
    [anon_sym_u00a7l] = ACTIONS(163),
    [anon_sym_u00a7L] = ACTIONS(163),
    [anon_sym_u00a7m] = ACTIONS(163),
    [anon_sym_u00a7M] = ACTIONS(163),
    [anon_sym_u00a7n] = ACTIONS(163),
    [anon_sym_u00a7N] = ACTIONS(163),
    [anon_sym_u00a7o] = ACTIONS(163),
    [anon_sym_u00a7O] = ACTIONS(163),
    [anon_sym_u00a7r] = ACTIONS(163),
    [anon_sym_u00a7R] = ACTIONS(163),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(163),
    [anon_sym_u00a7u00a7] = ACTIONS(163),
    [anon_sym_u00a7] = ACTIONS(165),
    [sym_text] = ACTIONS(165),
    [sym_newline] = ACTIONS(163),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(167), 1,
      aux_sym_variable_token1,
  [4] = 1,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
  [8] = 1,
    ACTIONS(171), 1,
      aux_sym_unknown_code_token1,
  [12] = 1,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(20)] = 0,
  [SMALL_STATE(21)] = 4,
  [SMALL_STATE(22)] = 8,
  [SMALL_STATE(23)] = 12,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_green, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_green, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_aqua, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_aqua, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_red, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_red, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_light_purple, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_light_purple, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_yellow, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_yellow, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_white, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_white, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_minecoin, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_minecoin, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fmt_obfuscate, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fmt_obfuscate, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fmt_bold, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fmt_bold, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fmt_strike, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fmt_strike, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fmt_underline, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fmt_underline, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fmt_reset, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fmt_reset, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fmt_italic, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fmt_italic, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_section, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_section, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_code, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unknown_code, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [169] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mccolor(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
